"""Pydantic models for Granola API responses with strict validation.

Generated from actual API response analysis of 40 documents.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Literal

import pydantic


class BaseModel(pydantic.BaseModel):
    """Base model with strict validation - no extra fields, all fields required unless Optional."""

    model_config = pydantic.ConfigDict(extra='forbid', strict=True)


# Nested models for structured data


class PersonName(BaseModel):
    fullName: str
    givenName: str | None = None
    familyName: str | None = None


class LinkedInInfo(BaseModel):
    """LinkedIn profile information."""

    handle: str


class TwitterInfo(BaseModel):
    """Twitter profile information."""

    handle: str


class EmploymentInfo(BaseModel):
    """Employment information."""

    name: str | None = None  # Company name
    title: str | None = None  # Job title


class PersonDetails(BaseModel):
    name: PersonName
    avatar: str | None = None  # Avatar is optional for attendees
    jobTitle: str | None = None  # Job title is optional
    linkedin: LinkedInInfo | None = None  # LinkedIn profile (enriched data)
    twitter: TwitterInfo | None = None  # Twitter profile (enriched data)
    employment: EmploymentInfo | None = None  # Employment info (enriched data)
    location: str | None = None  # Location (enriched data)


class CompanyDetails(BaseModel):
    name: str | None = None  # Can have name field
    logo: str | None = None  # Company logo URL (enriched data)
    domain: str | None = None  # Company domain (enriched data)
    description: str | None = None  # Company description (enriched data)


class GroupMember(BaseModel):
    """Member of a group attendee."""

    name: str
    email: str
    details: PersonInfo | None = None  # May contain nested person/company info


class GroupDetails(BaseModel):
    """Group attendee information."""

    members: Sequence[GroupMember]
    isTooBig: bool


class PersonInfo(BaseModel):
    person: PersonDetails | None = None  # May be None for group attendees
    company: CompanyDetails | None = None  # May be None for group attendees
    group: GroupDetails | None = None  # Present for group attendees


class Creator(BaseModel):
    name: str
    email: str
    details: PersonInfo


class Conferencing(BaseModel):
    url: str | None
    type: str | None
    title: str


class ManualAttendeeEdit(BaseModel):
    """Manual edit to meeting attendee list."""

    action: str  # e.g., "add"
    attendee_name: str
    attendee_email: str


class Attendee(BaseModel):
    """Meeting attendee with same structure as Creator."""

    name: str | None = None  # Some attendees only have email
    email: str
    details: PersonInfo | None = None  # May be partial/missing for some attendees


class People(BaseModel):
    title: str | None = None  # Optional in some documents
    creator: Creator
    attendees: Sequence[Attendee]
    created_at: str | None = None  # Optional in some documents
    sharing_link_visibility: str | None = None
    url: str | None = None
    conferencing: Conferencing | None = None
    manual_attendee_edits: Sequence[ManualAttendeeEdit] | None = None


class GoogleCalendarTime(BaseModel):
    dateTime: str
    timeZone: str


class GoogleCalendarCreator(BaseModel):
    self: bool | None = None
    email: str
    displayName: str | None = None


class GoogleCalendarOrganizer(BaseModel):
    self: bool | None = None
    email: str
    displayName: str | None = None


class GoogleCalendarReminders(BaseModel):
    useDefault: bool


class GeneratedLine(BaseModel):
    """Line generated by AI with match status."""

    text: str
    matches: bool


class CalendarAttendee(BaseModel):
    """Google Calendar event attendee."""

    email: str
    responseStatus: str
    self: bool | None = None
    displayName: str | None = None
    organizer: bool | None = None
    resource: bool | None = None  # True for room/resource attendees
    comment: str | None = None  # Attendee comment (e.g., OOO message)
    optional: bool | None = None  # True if attendee is optional


class ConferenceEntryPoint(BaseModel):
    """Entry point for conference (video, phone, etc.)."""

    entryPointType: str
    uri: str
    label: str | None = None
    pin: str | None = None
    regionCode: str | None = None


class ConferenceSolutionKey(BaseModel):
    """Key identifying the conference solution type."""

    type: str  # e.g., "hangoutsMeet"


class ConferenceSolution(BaseModel):
    """Conference solution details."""

    name: str
    iconUri: str
    key: ConferenceSolutionKey | None = None


class ConferenceCreateRequestStatus(BaseModel):
    """Status of conference create request."""

    statusCode: str  # e.g., "success"


class ConferenceCreateRequest(BaseModel):
    """Conference creation request details."""

    status: ConferenceCreateRequestStatus
    requestId: str
    conferenceSolutionKey: ConferenceSolutionKey


class ConferenceData(BaseModel):
    """Conference data for calendar event."""

    entryPoints: Sequence[ConferenceEntryPoint]
    conferenceSolution: ConferenceSolution
    conferenceId: str | None = None
    createRequest: ConferenceCreateRequest | None = None


class DocumentAttachment(BaseModel):
    """Attachment on a Granola document (image, etc.)."""

    id: str
    url: str
    type: str
    width: int
    height: int


class DisplayLocationEntry(BaseModel):
    """Single entry in Google Calendar event's displayLocations list.

    Example observed: {"text": "+1 310 564 6610", "source": "location"}
    """

    text: str
    source: str  # Observed: "location" — may have other values we haven't seen


class DisplayLocations(BaseModel):
    """Google Calendar's displayLocations field (added ~Apr 2026).

    Structure observed from live API:
      {"version": 1, "entries": [{"text": "...", "source": "location"}]}
    """

    version: int
    entries: Sequence[DisplayLocationEntry]


class GoogleCalendarEvent(BaseModel):
    id: str
    end: GoogleCalendarTime
    start: GoogleCalendarTime
    status: str
    iCalUID: str
    summary: str
    htmlLink: str
    organizer: GoogleCalendarOrganizer
    calendarId: str
    # Fields that may be missing in some API responses
    etag: str | None = None
    kind: str | None = None
    created: str | None = None
    updated: str | None = None
    eventType: str | None = None
    creator: GoogleCalendarCreator | None = None
    sequence: int | None = None
    reminders: GoogleCalendarReminders | None = None
    # Optional fields
    primaryCalendar: bool | None = None
    location: str | None = None
    description: str | None = None
    guestsCanInviteOthers: bool | None = None
    attendees: Sequence[CalendarAttendee] | None = None
    privateCopy: bool | None = None
    hangoutLink: str | None = None
    conferenceData: ConferenceData | None = None
    guestsCanModify: bool | None = None
    visibility: str | None = None
    attachments: Sequence[Mapping[str, str]] | None = None
    recurringEventId: str | None = None
    originalStartTime: GoogleCalendarTime | None = None
    guestsCanSeeOtherGuests: bool | None = None
    extendedProperties: Mapping[str, Mapping[str, str]] | None = None
    displayLocations: DisplayLocations | None = None  # Added by Google Calendar API ~Apr 2026


class ProseMirrorAttrs(BaseModel):
    """Attrs for ProseMirror nodes - allows extra fields for various node types."""

    model_config = pydantic.ConfigDict(extra='allow', strict=True)

    id: str | None = None  # Optional - not all nodes have id
    timestamp: str | None = None
    timestamp_to: str | None = pydantic.Field(default=None, alias='timestamp-to')


class ProseMirrorNode(BaseModel):
    """ProseMirror node - allows extra fields for text, marks, etc."""

    model_config = pydantic.ConfigDict(extra='allow', strict=True)

    type: str
    attrs: ProseMirrorAttrs | None = None
    content: Sequence[ProseMirrorNode] | None = None


class ProseMirrorDoc(BaseModel):
    """ProseMirror document - allows extra fields for complex nested structures."""

    model_config = pydantic.ConfigDict(extra='allow', strict=True)

    type: Literal['doc']
    content: Sequence[ProseMirrorNode]


class LastViewedPanel(BaseModel):
    """Panel data returned when include_last_viewed_panel=True."""

    document_id: str
    id: str
    created_at: str
    title: str
    content: ProseMirrorDoc | str  # ProseMirror JSON or HTML
    deleted_at: None = None
    template_slug: str
    last_viewed_at: str | None = None
    updated_at: str | None = None
    content_updated_at: str | None = None
    affinity_note_id: None = None
    original_content: str | None = None
    suggested_questions: None = None
    generated_lines: Sequence[GeneratedLine] | None = None
    ydoc_state: str | None = None  # Y.js document state
    ydoc_version: int | None = None  # Y.js document version


# Main document model


class GranolaDocument(BaseModel):
    """Strict model for Granola document with fail-fast validation."""

    # Required fields (always present and not null)
    id: str
    created_at: str
    notes: ProseMirrorDoc | None = None  # Can be None for some meetings
    user_id: str
    notes_plain: str | None = None  # Can be None for some meetings
    transcribe: bool
    updated_at: str
    public: bool
    meeting_end_count: int
    has_shareable_link: bool
    creation_source: str
    subscription_plan_id: str
    privacy_mode_enabled: bool
    workspace_id: str | None
    sharing_link_visibility: str
    last_indexed_at: str | None = None
    is_shared_direct: bool | None = None

    # Nullable fields (can be None)
    people: People | None  # Can be None for some meetings
    title: str | None
    cloned_from: str | None = None
    google_calendar_event: GoogleCalendarEvent | None
    deleted_at: str | None = None
    type: str | None
    overview: str | None = None
    chapters: None = None  # Always null
    notes_markdown: (
        str | None
    )  # Often empty/None for newer meetings - use panels endpoint instead
    selected_template: None = None  # Always null
    valid_meeting: bool | None
    summary: None = None  # Always null
    affinity_note_id: None = None  # Always null
    show_private_notes: bool | None
    attachments: Sequence[DocumentAttachment] | None
    hubspot_note_url: None = None  # Always null
    status: str | None = None
    external_transcription_id: str | None = None
    audio_file_handle: str | None = None
    visibility: None = None  # Always null
    notification_config: None = None  # Always null
    transcript_deleted_at: None = None  # Always null
    metadata: None = None  # Always null
    attio_shared_at: None = None  # Always null
    last_viewed_panel: LastViewedPanel | None = (
        None  # Only present when include_last_viewed_panel=True
    )
    was_trashed: bool | None = (
        None  # New field - indicates if document was previously trashed
    )
    is_primary_event_note: bool | None = None  # Primary note for calendar event
    ydoc_state: str | None = None  # Y.js document state
    ydoc_version: int | None = None  # Y.js document version
    zoom_rtms_permission: str | None = None  # Zoom RTMS permission for bot-free media streaming
    document_user_role: str | None = None  # User's role for this document
    is_scratchpad: bool | None = None  # Whether document is a scratchpad


class DocumentSetEntry(BaseModel):
    """Lightweight entry in the document set index.

    Each entry has exactly one of `owner` or `shared` set to True.
    The absent field is not present in the response (defaults to None).
    """

    updated_at: str
    owner: bool | None = None
    shared: bool | None = None
    has_ydoc: bool | None = None
    has_notes_ydoc: bool | None = None


class DocumentSetResponse(BaseModel):
    """Response from POST /v1/get-document-set.

    Returns a lightweight index of ALL documents (owned + shared + deleted).
    No pagination -- single call returns everything.
    """

    documents: Mapping[str, DocumentSetEntry]


class BatchDocumentsResponse(BaseModel):
    """Response from get-documents-batch API."""

    docs: Sequence[GranolaDocument]


# Simplified models for tool responses


class ParticipantInfo(BaseModel):
    """Participant information for meeting list items."""

    name: str
    email: str
    company_name: str | None = None  # Extracted from details.company.name
    job_title: str | None = None  # Extracted from details.person.jobTitle


class MeetingListItem(BaseModel):
    """Simplified meeting info for list views."""

    id: str
    title: str
    created_at: str
    type: str | None
    has_notes: bool
    participant_count: int
    is_shared: bool
    participants: Sequence[ParticipantInfo] | None = pydantic.Field(
        default=None, exclude_if=lambda v: v is None
    )


class DownloadResult(BaseModel):
    """Result from download operation."""

    path: str
    size_bytes: int


class TranscriptSegment(BaseModel):
    """Single segment of meeting transcript."""

    document_id: str
    id: str
    start_timestamp: str  # ISO 8601
    end_timestamp: str  # ISO 8601
    text: str
    source: str  # "microphone" or "system"
    is_final: bool
    transcriber_user_id: str | None = None


class TranscriptDownloadResult(BaseModel):
    """Result from transcript download operation with metadata."""

    path: str
    size_bytes: int
    segment_count: int
    duration_seconds: int
    microphone_segments: int
    system_segments: int


class DocumentPanel(BaseModel):
    """Panel from get-document-panels endpoint."""

    id: str
    created_at: str
    title: str
    document_id: str
    content: ProseMirrorDoc | str  # ProseMirror JSON or HTML
    template_slug: str | None = None
    deleted_at: str | None = None
    last_viewed_at: str | None = None
    updated_at: str
    content_updated_at: str | None = None
    affinity_note_id: str | None = None
    original_content: str | None = None  # Always HTML string
    suggested_questions: Sequence[str] | None = None
    generated_lines: Sequence[GeneratedLine] | None = None
    user_feedback: None = None
    ydoc_version: int | None = None  # Y.js document version


class NoteDownloadResult(BaseModel):
    """Result from note download with structural metadata."""

    path: str
    size_bytes: int
    # Structural metrics
    section_count: int  # Number of H3 headings
    bullet_count: int  # Total bullet points
    heading_breakdown: Mapping[str, int]  # {"h1": 1, "h2": 0, "h3": 5}
    # Content metrics
    word_count: int
    # Panel metadata
    panel_title: str
    template_slug: str | None


class PrivateNoteDownloadResult(BaseModel):
    """Result from private note download with metadata."""

    path: str
    size_bytes: int
    word_count: int
    line_count: int


class MeetingList(BaseModel):
    """Meeting list/collection with document IDs."""

    id: str
    title: str
    description: str | None
    visibility: str
    document_ids: Sequence[str]
    document_count: int
    created_at: str
    updated_at: str


class MeetingListsResult(BaseModel):
    """Result from getting meeting lists."""

    lists: Sequence[MeetingList]
    total_count: int


class DeleteMeetingResult(BaseModel):
    """Result from delete/undelete meeting operation."""

    success: bool
    document_id: str


class WorkspaceData(BaseModel):
    """Workspace data structure from API."""

    workspace_id: str
    slug: str
    display_name: str
    is_locked: bool
    created_at: str
    updated_at: str
    privacy_mode_enabled: bool
    sharing_link_visibility: str | None
    transcript_retention_hours: int | None
    transcript_retention_hours_updated_at: str | None
    logo_url: str | None
    company_type: str | None
    deleted_at: str | None
    allow_moving_notes: bool
    pre_call_email_enabled: bool
    affirmative_consent_enabled: bool
    in_meeting_copy_consent_message_banner_enabled: bool
    in_meeting_copy_consent_message_banner_message: str | None = None
    calendar_addon_api_key: str | None
    allow_transfer_notes: bool
    discoverable: bool
    chat_paste_enabled: bool
    allow_data_export: bool = True
    self_email_enabled: bool
    pre_call_email_blocklist: Sequence[str]
    pre_call_email_allowlist: Sequence[str]
    pre_call_email_large_meeting_threshold: int
    workos_organization_id: str | None = None
    sso_enabled: bool = False
    mcp_enabled: bool = False
    zoom_app_enabled: bool = False
    zoom_consent_enabled: bool = False
    zoom_consent_settings: Mapping[str, object] | None = None
    google_meet_consent_enabled: bool = False
    google_meet_consent_settings: Mapping[str, object] | None = None
    zoom_rtms_enabled: bool = False
    user_notes_api_enabled: bool = False
    allow_external_invites: bool = True
    allow_external_sharing: bool = True
    allow_public_folders: bool = True
    is_directory_provisioned_user: bool = False
    directory_sync_enabled: bool = False


class WorkspaceItem(BaseModel):
    """Workspace item with role and plan type."""

    workspace: WorkspaceData
    role: str  # e.g., "admin", "member"
    plan_type: str  # e.g., "free", "pro"


class WorkspacesResponse(BaseModel):
    """API response from get-workspaces endpoint."""

    workspaces: Sequence[WorkspaceItem]


class WorkspaceInfo(BaseModel):
    """Simplified workspace info for MCP tool results."""

    workspace_id: str
    display_name: str
    slug: str
    is_locked: bool
    logo_url: str | None
    created_at: str
    role: str
    plan_type: str
    privacy_mode_enabled: bool


class ListWorkspacesResult(BaseModel):
    """Result from list_workspaces tool."""

    workspaces: Sequence[WorkspaceInfo]
    total_count: int


class CreateWorkspaceResult(BaseModel):
    """Result from create_workspace tool."""

    workspace_id: str
    display_name: str
    slug: str
    logo_url: str | None
    created_at: str
    has_business_trial: bool


class DeleteWorkspaceResult(BaseModel):
    """Result from delete_workspace tool."""

    workspace_id: str
    deleted_at: str


# Meeting Update Models


class AttendeeUpdate(BaseModel):
    """Attendee information for updates."""

    name: str
    email: str
    job_title: str | None = None
    company_name: str | None = None


class UpdateMeetingResult(BaseModel):
    """Result from /v1/update-document API."""

    id: str
    ydoc_state: str | None = None  # Y.js document state
    ydoc_resolution: str | None = None  # Y.js document resolution status


# URL Resolution Models


class ResolveUrlResult(BaseModel):
    """Result from resolving a Granola URL to document ID."""

    document_id: str
    url_type: str  # "sharing" or "direct"
    original_url: str
    resolved_from_redirect: bool = False
